modules/attd/controllers/ReportController.php
<?php

namespace app\modules\attd\controllers;

use app\models\User;
use app\modules\attd\models\AttendanceOutsideService;
use app\modules\attd\models\AttendanceOvertime;
use app\modules\attd\models\Leave;
use app\modules\attd\models\LeaveType;
use yii\data\ArrayDataProvider;
use app\modules\attd\models\Attendance;
use yii\db\Query;
use Mpdf;
use yii\helpers\Url;
use Yii;


class ReportController extends \yii\web\Controller
{
    public function actionIndex()
    {
        return $this->render('index');
    }

    //สารบัญการค้นหา
    //Report Clock_in PDF = ReportClockin
    //Report Leave PDF = ReportLeave
    //Report Overtime PDF = ReportOvertime

    public function actionReportClockinByPerson()
    {
        $data = [];
        $post = Yii::$app->request->post();

        if ($post) {
            $date_range = explode(' - ', $post['date_range']);
            $start_date = $date_range[0];
            $end_date = $date_range[1];
            $start_time = strtotime($start_date);
            $end_time = strtotime($end_date);
            for ($i = $start_time; $i <= $end_time; $i += 86400) {
                $list[] = date('Y-m-d', $i);
            }
            foreach ($list as $item) {
                $data[] = $item;
            }
        }

        return $this->render('report-clockin-by-person', [
            'SelectDay' => $data,
            'pagination' => ['pageSize' => 50],

        ]);
    }

//รายงานการลารายบุคคล
    public
    function actionReportLeaveByPerson()
    {
        $query = [];
        $post = Yii::$app->request->post();
        if ($post) {
            $date_range = explode(' - ', $post['date_range']);
            $query = Leave::find()
                ->where(['approve_status' => 2])
                ->andWhere(['between', 'leave_start', $date_range[0], $date_range[1]])
                ->orderBy(['leave_start' => SORT_ASC])
                ->asArray()
                ->all();
            $LeaveCount = count($query);
        }
        $dataProvider = new ArrayDataProvider([
            'allModels' => $query,
            'pagination' => false,
        ]);

        return $this->render('report-leave-by-person', [
            'dataProvider' => $dataProvider,
            'LeaveCount' => $post ? $LeaveCount : null,
            'pagination' => 50,
        ]);
    }

    public function actionReportLeaveByType()
    {
        $post = Yii::$app->request->post();
        $current_leave = 0;
        if ($post) {
            $date_range = explode(' - ', $post['date_range']);
            $query = Leave::find()
                ->where(['between', 'leave_start', $date_range[0], $date_range[1]])
                ->andWhere(['leave_type' => $post['leave_type']])
                ->andWhere(['user_id' => $post['user_id']])
                ->orderBy(['leave_start' => SORT_ASC])
                ->asArray()
                ->all();
            $LeaveCount = count($query);

            $type = LeaveType::find()
                ->where(['id' => $post['leave_type']])
                ->one();

            $dataProvider = new ArrayDataProvider([
                'allModels' => $query,
                'pagination' => false,
            ]);

        }
        return $this->render('report-leave-by-type', [
            'dataProvider' => $post ? $dataProvider : null,
            'leaveCount' => $post ? $LeaveCount : null,
            'current_leave' => $current_leave,
            'type' => $post ? $type : null,
            'pagination' => 50,
        ]);
    }

//รายงานทำงานล่วงเวลา
    public
    function actionReportOvertimeByPerson()
    {
        $post = Yii::$app->request->post();
        if ($post) {
            $date_range = explode(' - ', $post['date_range']);
            $overtime_query = AttendanceOvertime::find()
                ->Where(['user_id' => $post['user_id']])
                ->andWhere(['between', 'overtime_date', $date_range[0], $date_range[1]])
                ->andWhere(['status' => 2])
                ->all();
        }
        return $this->render('report-overtime-by-person', [
            'overtime_person' => $post ? $overtime_query : null,
        ]);
    }

//รายงานการลงเวลารายวัน
    public
    function actionReportClockinPerDay()
    {
        $post = Yii::$app->request->post();
        if ($post) {
            $timeScan = (new Query())
                ->select('"user".id, "user".username, "user".full_name, 
                "attendance".user_id, "attendance".att_date, "attendance".att_check , "attendance".att_checkout')
                ->from('user')
                ->leftJoin('attendance', '"user".id = "attendance".user_id')
                ->where(['att_date' => $post['datetime']])
                ->orderBy(['att_check' => SORT_ASC])
                ->all();
        }
        return $this->render('report-clockin-per-day', [
            'time' => $post ? $timeScan : null,
        ]);
    }

    public
    function actionReportSummaryClockin()
    {
        $post = Yii::$app->request->post();
        if ($post) {
            $user = User::find()->where(['status' => 10])
                ->orderBy(['id' => SORT_ASC])
                ->all();
            $date_range = explode(' - ', $post['date_range']);
            $start_date = $date_range[0];
            $end_date = $date_range[1];
            $start_time = strtotime($start_date);
            $end_time = strtotime($end_date);
            for ($i = $start_time; $i <= $end_time; $i += 86400) {
                $list[] = date('Y-m-d', $i);
            }
            foreach ($list as $item) {
                $data[] = $item;
            }

            $start_check = $date_range[0];
            $end_check = date('Y-m-d');
            $start_time1 = strtotime($start_check);
            $end_time1 = strtotime($end_check);
            for ($i = $start_time1; $i <= $end_time1; $i += 86400) {
                $list1[] = date('Y-m-d', $i);
            }
            foreach ($list1 as $items) {
                $data2[] = $items;
            }
        }
        return $this->render('report-summary-clockin', [
            'date' => $post ? $data : null,
            'get_user' => $post ? $user : null,
            'check_date' => $post ? $data2 : null
        ]);
    }


//PDF การลงเวลา
    public
    function actionReportClockin($id, $start, $end)
    {
        $data = [];
        $start_date = $start;
        $end_date = $end;
        $start_time = strtotime($start_date);
        $end_time = strtotime($end_date);
        for ($i = $start_time; $i <= $end_time; $i += 86400) {
            $list[] = date('Y-m-d', $i);
        }
        foreach ($list as $item) {
            $data[] = $item;
        }

        $pdf_content = $this->renderPartial('reportpdf-clockin', [
            'selectday' => $data,
            'id' => $id

        ]);

        $params = Yii::$app->params;
        $fontDirs = $params['defaultConfig']['fontDir'];
        $fontData = $params['defaultFontConfig']['fontdata'];

        $mpdf = new Mpdf\Mpdf([
            'fontDir' => array_merge($fontDirs, [
                Url::base() . 'fonts/THSarabun',
            ]),
            'fontdata' => $fontData + ['thsarabun' => $params['SetTHSarabun']],
            'default_font' => 'thsarabun',
            'format' => 'A4',
            'mode' => 'utf-8',
            'default_font_size' => 18,
            'margin_top' => 10,
            'margin_left' => 10,
            'margin_right' => 10,
            'margin_bottom' => 10,
        ]);
        $stylesheet = file_get_contents(Url::base() . 'css/bootstrap.css');
        $mpdf->WriteHTML($stylesheet, 1);
        $mpdf->WriteHTML($pdf_content, 2);
        $mpdf->Output();
    }

    public function actionReportpdfLeaveByType($id, $start, $end, $type)
    {
        $query = Leave::find()
            ->where(['between', 'leave_start', $start, $end])
            ->andWhere(['leave_type' => $type])
            ->orderBy(['leave_start' => SORT_ASC])
            ->asArray()
            ->all();

        $LeaveCount = count($query);

        $typemode = LeaveType::find()
            ->where(['id' => $type])
            ->one();

        $content = $this->renderPartial('reportpdf-leave-by-type', [
            'data' => $query,
            'leave_count' => $LeaveCount,
            'type' => $typemode
        ]);

        $footer = $this->renderPartial('_footer');

        $format = [
            "papersize" => 'A4',
            "content" => $content,
            "orientation" => 'P',
            "footer" => $footer
        ];

        $title = 'รายงานสรุปการลา';
        $this->actionGeneratePDF($format, 10, 10, 10, 10, $title, true);
    }

//PDF การลางาน
    public
    function actionReportLeave($start, $end)
    {
        $queryLeave = Leave::find()
            ->where(['approve_status' => 2])
            ->andWhere(['between', 'leave_start', $start, $end])
            ->orderBy(['leave_start' => SORT_ASC])
            ->all();

        $pdf_content = $this->renderPartial('reportpdf-leave', [
            'model' => $queryLeave,
            'start_date' => $start,
            'end_date' => $end,
        ]);

        $params = \Yii::$app->params;
        $fontDirs = $params['defaultConfig']['fontDir'];
        $fontData = $params['defaultFontConfig']['fontdata'];
        $mpdf = new Mpdf\Mpdf([
            'fontDir' => array_merge($fontDirs, [
                Url::base() . 'fonts/THSarabun',
            ]),
            'fontdata' => $fontData + ['thsarabun' => $params['SetTHSarabun']],
            'default_font' => 'thsarabun',
            'format' => 'A4',
            'mode' => 'utf-8',
            'default_font_size' => 16,
            'margin_top' => 10,
            'margin_left' => 10,
            'margin_right' => 10,
            'margin_bottom' => 10,
        ]);
        $stylesheet = file_get_contents(Url::base() . 'css/bootstrap.css');
        $mpdf->WriteHTML($stylesheet, 1);
        $mpdf->WriteHTML($pdf_content, 2);
        $mpdf->Output();

modules/attd/views/report/_footer.php
<h4 class="pull-right" style="font-weight: bold">สร้างวันที่ <?= date('Y-m-d H:i:s')?></h4>

modules/attd/views/report/_summary_footer.php
<?php
/**
 * Created by PhpStorm.
 * User: shiranko
 * Date: 17/12/2561
 * Time: 14:39 น.
 */

?>

<div class="pull-left" style="font-size: 14px; font-style: normal">
    <?php echo 'สร้างเมื่อ '. Yii::$app->datetimeManage->dtFormat(date('Y-m-d')) . ' เวลา '  . date('H:i:s') ?>
</div>

modules/attd/views/report/_summary_header.php
<?php
/**
 * Created by PhpStorm.
 * User: shiranko
 * Date: 17/12/2561
 * Time: 14:37 น.
 */

?>
<div style="font-style: normal">
    <p style="font-size: 14px">
        สรุปผลการลงเวลาตามช่วงวันที่
    </p>
</div>

modules/attd/views/report/index.php
<?php
/* @var $this yii\web\View */
$this->registerCss("
    .padding-border {
        padding: 10px 20px;
    }
");
$this->title = "Report";
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="report">
    <div class="clearfix">
        <div class="row">
            <div class="col-md-6">
                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class="padding-border box-title text-olive"><i class="fa fa-file-pdf-o"></i> <small></small>รายงานการลงเวลา</h3>
                    </div>
                    <div class="box-body">
                        <div class="box-group">
                            <div class="row fontawesome-icon-list">
                                <div class="padding-border fa-hover col-md-6 col-sm-6 col-xs-12"><a href="/attd/report/report-clockin-by-person"><i class="fa fa-file-pdf-o"></i>รายงานการลงเวลารายบุคคลตามช่วงเวลา</a></div>
<!--                                <div class="padding-border fa-hover col-md-4 col-sm-4 col-xs-12"><a href="/attd/report/report-clockin-per-day"><i class="fa fa-file-pdf-o"></i> รายงานการลงเวลารายวัน</a></div>-->
                                <div class="padding-border fa-hover col-md-6 col-sm-6 col-xs-12"><a href="/attd/report/report-summary-clockin"><i class="fa fa-file-pdf-o"></i>รายงานสรุปผลการลงเวลาตามช่วงเวลา</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class="padding-border box-title text-olive"><i class="fa fa-file-pdf-o"></i> <small></small>รายงานการลา</h3>
                    </div>
                    <div class="box-body">
                        <div class="box-group">
                            <div class="row fontawesome-icon-list">
                                <div class="padding-border fa-hover col-md-4 col-sm-4 col-xs-12"><a href="/attd/report/report-leave-by-person"><i class="fa fa-file-pdf-o"></i> รายงานการลาตามช่วงวันที่</a></div>
                                <div class="padding-border fa-hover col-md-4 col-sm-4 col-xs-12"><a href="/attd/report/report-leave-by-type"><i class="fa fa-file-pdf-o"></i> รายงานสรุปการลาตามประเภท</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="box box-solid">
                    <div class="box-header with-border">
                        <h3 class="padding-border box-title text-olive"><i class="fa fa-file-pdf-o"></i> <small></small>การทำงานนอกสถานที่ของพนักงาน</h3>
                    </div>
                    <div class="box-body">
                        <div class="box-group">
                            <div class="row fontawesome-icon-list">
                                <div class="padding-border fa-hover col-md-4 col-sm-4 col-xs-12"><a href="/attd/report/report-out-side"><i class="fa fa-file-pdf-o"></i> รายงานการทำงานนอกสถานที่</a></div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

modules/attd/views/report/report-clockin-by-person.php
<?php

use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use yii\helpers\Html;
use kartik\daterange\DateRangePicker;
use yii\widgets\Pjax;
use app\modules\attd\models\Attendance;
use yii\db\Query;


/**
 * Created by PhpStorm.
 * User: magimari
 * Date: 30/8/2561
 * Time: 11:24 น.
 */
$this->title = "รายงานการลงเวลารายบุคคลตามช่วงวันที่";
$this->params['breadcrumbs'][] = $this->title;

$this->registerCss("
    .style-inline{
        float: right;
    }
");

$user = ArrayHelper::map(\app\models\User::find()->where(['status' => 10])->orderBy(['id' => SORT_ASC])->all(), 'id', 'full_name');
if ($post = Yii::$app->request->post()) {
    $user_value = $post['user_id'];
    $date_data = $post['date_range'];
}

function userName($id)
{
    return Attendance::findOne($id);
}

$late = '09:00:01';

?>

<?php Pjax::begin() ?>

<?php $form = ActiveForm::begin(); ?>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-3">
            <?php echo '<label class="control-label">ชื่อพนักงาน</label>';
            echo Select2::widget([
                'name' => 'user_id',
                'data' => $user,
                'value' => !empty($user_value) ? $user_value : '',
                'options' => ['placeholder' => 'Select a Username',],
                'pluginOptions' => [
                    'allowClear' => true,
                ],
            ]);
            ?>
        </div>



        <div class="col-md-3">
            <?php echo '<label class="control-label">ช่วงเวลาที่ต้องการค้นหา</label>';
            echo DateRangePicker::widget([
                'name' => 'date_range',
                'data' => date('Y-m-d'),
                'presetDropdown' => true,
                'hideInput' => true
            ]);
            ?>
        </div>

        <div class="col-md-3">
            <br>
            <p style="padding-top: 5px;">
                <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>

            </p>
        </div>

        <div class="col-md-3">
            <?php
            $post = Yii::$app->request->post();
            if (!empty($post)) :
                $date_range = explode(' - ', $post['date_range']);
                ?>
                <div style="float: right; padding-top: 20px">
                    <?= Html::a('Generate PDF', ['report/report-clockin', 'id' => $post['user_id'], 'start' => $date_range[0], 'end' => $date_range[1]], ['target' => '_blank', 'data-pjax' => "0", 'class' => 'btn btn-success']) ?>
                </div>
            <?php endif; ?>
        </div>

    </div>
</div>


<?php $form = ActiveForm::end(); ?>
<br/>
<?php
$post = Yii::$app->request->post();
if ($post) : ?>
    <table class="table table-bordered">
        <tr>
            <th>วัน</th>
            <th>วันที่</th>
            <th>ชื่อผู้สแกน</th>
            <th>เวลาสแกนเข้า</th>
            <th>เวลาสแกนออก</th>
            <th>รวม</th>
            <th>หมายเหตุ</th>
        </tr>
        <?php foreach ($SelectDay as $item):
            $query = (new Query())
                ->select('"user".id, "user".username, "user".role_shift, "user".full_name, "user".status,
                  "attendance".att_date, "attendance".att_check, "attendance".att_checkout,"attendance".overtime, "attendance".att_status, "attendance".leave_id,
                   "shift".come_late_time, "shift".back_early_time, "shift".no_attend_time , "holiday".holiday_name, "holiday".holiday_date')
                ->from('user')
                ->leftJoin('attendance', '"user".id="attendance".user_id')
                ->leftJoin('shift', '"user".role_shift="shift".id')
                ->leftJoin('holiday', '"holiday".holiday_date = "attendance".att_date')
                ->where(['user_id' => $post['user_id']])
                ->andWhere(['status' => 10])
                ->andWhere(['att_date' => $item])
                ->orderBy(['att_date' => SORT_ASC])
                ->one();

            $day = date("l", strtotime($item));
            $holiday = \app\modules\attd\models\Holiday::find()->where(['holiday_date' => $item])->one();
            ?>
            <?php if (!empty($holiday)): ?>
            <tr>
                <td><?= Yii::$app->datetimeManage->dateName($day) ?> </td>
                <td><?= Yii::$app->datetimeManage->dtFormat($holiday['holiday_date']); ?></td>
                <td style="font-weight: bold"><?= $holiday['holiday_name'] ?></td>
                <td style="font-weight: bold"><?= $holiday['description'] ?></td>
                <td></td>
                <td><span class="label label-default" style="font-size: 13px">วันหยุด</span></td>
            </tr>
        <?php else: ?>
            <tr>
                <td><?= Yii::$app->datetimeManage->dateName($day) ?> </td>
                <td><?= Yii::$app->datetimeManage->dtFormat($item); ?></td>
                <td><?= $query['full_name'] ?></td>
                <td><?= substr($query['att_check'], 11) ?></td>
                <td><?= substr($query['att_checkout'], 11) ?></td>
                <td>
                    <?php
                    $time1 = substr($query['att_check'], 11, 5);
                    $time2 = substr($query['att_checkout'], 11, 5);
                    $diffTime = differenceInHours($time1, $time2);
                    if ($query['att_date'] == date('Y-m-d')) {
                        echo '';
                    }
                    elseif (empty($time2)){
                        echo '';
                    }
                    elseif ($query['att_date'] < date('Y-m-d')) {
                        echo round($diffTime) - 1 . " ชั่วโมง ";
                    }
                    ?>
                </td>
                <?php if ($day == 'Saturday' || $day == 'Sunday'): ?>
                    <td><span class="label label-primary"
                              style="font-size: 13px"><?= '' ?></span></td>
                <?php elseif ($query['att_status'] != null): ?>
                    <td><span class="label label-info" style="font-size: 13px"><?= $query['att_status'] ?></span></td>
                <?php elseif ($query['att_check'] != null && substr($query['att_check'], 11) > $late): ?>
                    <td><span class="label label-warning" style="font-size: 13px">สาย</span></td>
                <?php elseif ($query['att_check'] != null && substr($query['att_check'], 11) < $late): ?>
                    <td><span class="label label-success" style="font-size: 13px">ปกติ</span></td>
                <?php elseif ($query['att_check'] == null): ?>
                    <td><span class="label label-danger" style="font-size: 13px">ไม่ได้สแกนนิ้ว/ขาดงาน</span></td>
                <?php endif; ?>
            </tr>
        <?php endif; ?>
        <?php endforeach;
        ?>
    </table>
<?php endif; ?>

<?php Pjax::end() ?>

<?php
function differenceInHours($startdate, $enddate)
{
    $starttimestamp = strtotime($startdate);
    $endtimestamp = strtotime($enddate);
    $difference = abs($endtimestamp - $starttimestamp) / 3600;
    return $difference;
}

if (!empty($_POST["submit"])) {
    $hours_difference = differenceInHours($_POST["startdate"], $_POST["enddate"]);
    $message = "The Difference is " . $hours_difference . " hours";
}
?>

modules/attd/views/report/report-leave-by-type.php
<?php

//use yii\grid\GridView;
use yii\helpers\Html;
use app\modules\attd\models\Leave;
use yii\widgets\Pjax;
use yii\helpers\ArrayHelper;
use kartik\select2\Select2;
use yii\widgets\ActiveForm;
use kartik\daterange\DateRangePicker;
use kartik\grid\GridView;

/**
 * Created by PhpStorm.
 * User: magimari
 * Date: 30/8/2561
 * Time: 11:25 น.
 */

$this->title = "รายงานสรุปการลา";
$this->params['breadcrumbs'][] = $this->title;

$post = Yii::$app->request->post();

$holidayLeave = 7;
$sickLeave = 30;
$errandLeave = 7;


$this->registerCss("
    .style-td{
        font-size: 16px; 
        line-height: 1cm;
    }
");

$post = Yii::$app->request->post();
$user = ArrayHelper::map(\app\models\User::find()->orderBy(['id' => SORT_ASC])->all(), 'id', 'full_name');
$leave_tpye = ArrayHelper::map(\app\modules\attd\models\LeaveType::find()->orderBy(['id' => SORT_ASC]) ->all(), 'id', 'leave_type_name');
if ($post) {
    $date_data = $post['date_range'];
}

function leave($id)
{
    return Leave::findOne($id);
}

?>
<?php Pjax::begin(); ?>
<?php $form = ActiveForm::begin(); ?>

<div class="row">
    <div class="col-md-3">
        <?php echo '<label class="control-label">ชื่อพนักงาน</label>';
        echo Select2::widget([
            'name' => 'user_id',
            'data' => $user,
            'value' => $post ? $user : null ,
            'options' => ['placeholder' => 'Select a Username',],
            'pluginOptions' => [
                'allowClear' => true,
            ],
        ]);
        ?>
    </div>

    <div class="col-md-3">
        <?php echo '<label class="control-label">ประเภทการลา</label>';
        echo Select2::widget([
            'name' => 'leave_type',
            'data' => $leave_tpye,
            'value' => $post ?  $leave_tpye : null,
            'options' => ['placeholder' => 'Select a Username',],
            'pluginOptions' => [
                'allowClear' => true,
            ],
        ]);
        ?>
    </div>

    <div class="col-md-3">
        <?php echo '<label class="control-label">วันที่ต้องการค้นหา</label>';
        echo DateRangePicker::widget([
            'name' => 'date_range',
            'data' => date('Y-m-d') . " - " . date('Y-m-d'),
            'presetDropdown' => true,
            'hideInput' => true
        ]);
        ?>
    </div>

    <div class="col-md-1">
        <br>
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
    </div>

    <div class="form-group">
        <?php
        $post = Yii::$app->request->post();
        if (!empty($post)) :
            $date_range = explode(' - ', $post['date_range']);
            ?>
            <div style="float: right; padding-top: 20px; padding-right: 30px">
                <?= Html::a('Generate PDF', ['report/reportpdf-leave-by-type', 'id' => $post['user_id'], 'start' => $date_range[0], 'end' => $date_range[1], 'type' => $post['leave_type']], ['target' => '_blank', 'data-pjax' => "0", 'class' => 'btn btn-success']) ?>
            </div>
        <?php endif; ?>
    </div>


</div>

<?php $form = ActiveForm::end(); ?>

<br>

<?php
$post = Yii::$app->request->post();
if ($post) : ?>
<div class="row">
    <div class="col-md-12">
        <?php echo
        GridView::widget([
            'dataProvider' => $dataProvider,
            'responsive' => true,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                [
                    'attribute' => 'username',
                    'label' => 'ชื่อผู้ใช้งาน',
                ],
                [
                    'attribute' => 'leave_type',
                    'label' => 'ประเภทการลา',
                    'value' => function ($model) {
                        $levObj = \leave($model['id']);
                        return $levObj->typeName;
                    }
                ],
                [
                    'attribute' => 'leave_start',
                    'label' => 'วันที่ลา',
                ],
                [
                    'attribute' => 'description',
                    'label' => 'สาเหตุการลา',
                ],
                [
                    'attribute' => 'approve_by',
                    'label' => 'บันทึกโดย',
                ]
            ],
            'panel' => [
                'type' => GridView::TYPE_PRIMARY,
                'heading' => 'รายการลางานตามประเภท'
            ],
        ])
        ?>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="panel panel-primary">
            <div class="panel-heading" style="font-size: 18px"><strong>สรุปวันลา</strong></div>
            <div class="panel-body">
                <table class="table table-hover">
                    <tr>
                        <td><strong>ประเภทการลา:  <?= $type['leave_type_name'] ?> &nbsp; จำนวนวันที่ลาแล้ว: &nbsp; <?= $leaveCount?> &nbsp; วัน</strong></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>


<?php endif; ?>


<?php Pjax::end(); ?>

modules/attd/views/report/reportpdf-clockin-per-day.php
<?php

/**
 * Created by PhpStorm.
 * User: shiranko
 * Date: 14/12/2561
 * Time: 18:34 น.
 */

use yii\helpers\Html;
use yii\db\Query;

$this->title = 'รายงานการลงเวลาเข้า-ออกรายวัน';

$end_time ='';
$i = 0;

//var_dump($timescan);
//exit();
?>

<div class="container">
    <h1 style="font-weight: bold"><?= Html::encode($this->title) ?></h1>
</div>
<!---->

<div>
    <h2>รายงานการสแกนนิ้วรายวัน</h2>
    <table class="table table-bordered">
        <tr>
            <th>วันที่</th>
            <th>ชื่อผู้ใช้งาน</th>
            <th>เวลาเข้า</th>
            <th>เวลาออก</th>
        </tr>
        <?php foreach ($timescan as $item): ?>
        <tr>
            <td><?= $item['att_date'] ?></td>
            <td><?= $item['full_name'] ?></td>
            <td><?= $item['att_check'] ?></td>
            <td><?= $item['att_checkout'] ?></td>
        </tr>
        <?php endforeach; ?>
    </table>
</div>

modules/attd/views/report/reportpdf-out-side.php
<?php
/**
 * Created by PhpStorm.
 * User: akinochan
 * Date: 26/3/2562
 * Time: 11:36 น.
 */

//$this->title = 'รายงานสรุปการลา';

function username($id)
{
    return \app\modules\attd\models\AttendanceOutsideService::findOne($id);
}
?>
<h1><?= $title ?></h1>

<div>
    <table class="table table-bordered">
        <tr>
            <th>User Name</th>
            <th>วันที่</th>
            <th>ประเภท</th>
            <th>สถานที่</th>
            <th>รายละเอียด</th>
            <th>ผู้บันทึก</th>
        </tr>
        <?php foreach ($data as $value) : ?>
            <tr>
                <td style="width: 80px"><?= username($value['id'])->userName ?></td>
                <td style="width: 90px"><?= Yii::$app->datetimeManage->dtFormat($value['outside_date_start']) ?></td>
                <td style="width: 80px"><?= username($value['id'])->typeName ?></td>
                <td style="width: 120px"><?= $value['outside_province'] ?></td>
                <td style="width: 180px"><?= $value['detail'] ?></td>
                <td style="width: 60px"><?= username($value['id'])->approve ?></td>
            </tr>
        <?php endforeach;?>
    </table>
</div>